config/routes.rb
Rails.application.routes.draw do
  # main routes
  get '/', to: 'main#top', as: 'home'
  get 'login', to: 'main#login', as: 'login'
  post 'login', to: 'main#login_service', as: 'login_service'
  get 'registration', to: 'main#registration', as: 'registration'
  post 'registration', to: 'main#registration_service', as: 'registration_service'
  get 'account/:user_id', to: 'main#account', as: 'account'
  get 'account_info/:user_id', to: 'main#account_info', as: 'account_info'
  put 'account_info/:user_id', to: 'main#account_info_service', as: 'account_info_service'
  get 'delete_account/:user_id', to: 'main#delete_account', as: 'delete_account'
  post 'delete_account/:user_id', to: 'main#delete_account_service', as: 'delete_account_service'
  post 'logout_service', to: 'main#logout_service', as: 'logout_service'
  # main routes friend function
  get 'all_users/:user_id', to: 'main#all_users', as: 'all_users'
  get 'other_user/:user_id/:other_user_id', to: 'main#other_user', as: 'other_user'
  post 'other_user/:user_id/:other_user_id/:pending_flg', to: 'main#other_user_service', as: 'other_user_service'
  get 'request_list/:user_id', to: 'main#request_list', as: 'request_list'
  post 'request_list/:user_id/:other_user_id/:request_flg', to: 'main#request_service', as: 'request_service'
  get 'friend_list/:user_id', to: 'main#friend_list', as: 'friend_list'
  # posts routes
  get 'feed/:user_id', to: 'posts#feed', as: 'feed'
  get 'upload/:user_id', to: 'posts#upload', as: 'upload'
  post 'upload/:user_id', to: 'posts#upload_service', as: 'upload_service'
  get 'edit/:user_id/:post_id', to: 'posts#edit', as: 'edit'
  put 'edit/:user_id/:post_id', to: 'posts#edit_service', as: 'edit_service'
  get 'delete/:user_id/:post_id', to: 'posts#delete', as: 'delete'
  delete 'delete/:user_id/:post_id', to: 'posts#delete_service', as: 'delete_service'
  # reactions routes
  post 'like/:user_id/:post_id', to: 'reactions#like', as: 'like'
  delete 'like_cancel/:user_id/:post_id', to: 'reactions#like_cancel', as: 'like_cancel'
end

app/models/post.rb
class Post < ApplicationRecord
  # validates :content_text, presence: true
  # validates :image, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def feed
    @posts = Post.all.order(updated_at: :desc)
  end

  def upload
  end

  def upload_service
    isRender_flag = true
    post_info = Post.create!(
      user_id: session[:user_id]
    )
    # validetionによって、post_idの取得ができないので、validation off のelse renderで対処
    if params[:post_image]
      logger.info("id = #{post_info.id}")
      post_image = params[:post_image]
      File.binwrite("public/post_images/#{post_info.id}.jpg", post_image.read)
      post_info.update(image: "#{post_info.id}.jpg")
      logger.info("[info]: imageが作成されました。")
    else
      isRender_flag = false
      logger.info("[info]: render flag")
    end

    if params[:content_text] 
      content_text = params[:content_text]
      if content_text.present?
        post_info.content_text = params[:content_text]
        logger.info("[info]: content_textが作成されました。")
      else
        isRender_flag = false
        logger.info("[info]: render flag")
      end
    else
      isRender_flag = false
      logger.info("[info]: render flag")
    end

    if post_info.valid? && isRender_flag
      logger.info("[info]: redirectが成功しました。")
      redirect_to feed_path(session[:user_id])
    else
      post_info.destroy!
      logger.info("[info]: imageまたはcontent_textが未入力のためpost_infoはdestroyされました。")
      flash.now[:message] = "image or text is blank!"
      logger.info("[info]: renderされました。")
      render("/posts/upload")
    end
  end

  def edit
    @posted_info = Post.find_by(id: params[:post_id], user_id: session[:user_id])
  end

  def edit_service
    post_info = Post.find_by(id: params[:post_id], user_id: session[:user_id])
    post_info.content_text = params[:edited_text]
    if post_info.save!
      flash.now[:message] = "Editting was succeed!"
      redirect_to feed_path(session[:user_id])
    else
      flash.now[:message] = "Edit faild! Try again!"
      render("/posts/edit")
    end
  end

  def delete
  end

  def delete_service
    reactions = Reaction.where(post_id: params[:post_id])
    # delete_flag 1 -> 2 論理削除
    reactions.each do |reaction|
      logger.info("[info]: #{reaction}")
      reaction.d_flag = 2
      if reaction.save!
        logger.info("[info]: delete_flagを変更し、reactionを論理削除しました。")
      else
        render("posts/delete")
      end
    end
    post_info = Post.find_by(id: params[:post_id], user_id: session[:user_id])
    if post_info.destroy!
      redirect_to feed_path(session[:user_id])
    else
      render("/posts/feed")
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/delete.html.slim
div.delete-background
  h1 delete
  p Are You Sure To Delete This Post?
  div.delete-select
    = link_to "Delete", delete_path(session[:user_id], params[:post_id]), method: :delete
    = link_to "Cancel", feed_path(session[:user_id])

app/views/posts/edit.html.slim
div.edit-background
  h1 Edit
  = image_tag "/post_images/#{@posted_info.image}", alt: 'post_image'
  div.form-template
    = form_with model: @post_info, local: true, method: :put do |f|
      p
        = f.label :Comment
      = f.text_field :edited_text, value: @posted_info.content_text
      p
        = f.submit "Edit", class:"edit-btn"

app/views/posts/feed.html.slim
div.feed-background
  h1 Feed
  = link_to "New Post", upload_path(session[:user_id]), class:"new-post-btn"
  - @posts.each do |post|
    div.post-box
      = image_tag "/post_images/#{post.image}", alt: 'post_image'
      div.content-text
        p
          = post.content_text
        p
          = post.updated_at.strftime("%Y/%-m/%-d %H:%M")
        p
          = "Posted by #{post.user_id}"
      div.post-edit
        - if post.user_id == session[:user_id]
          = link_to "Edit", edit_path(session[:user_id], post.id)
          = link_to "Delete", delete_path(session[:user_id], post.id)
        - if Reaction.find_by(post_id: post.id, user_id: session[:user_id]) == nil
          = link_to "Like", like_path(session[:user_id], post.id), method: :post, remote: true
        - else
          = link_to "Cancel", like_cancel_path(session[:user_id], post.id), method: :delete, remote: true
        div.reaction
          = Reaction.where(post_id: post.id).count

app/views/posts/upload.html.slim
div.new-post
  h1 New Post!
  = link_to "Feed", feed_path(session[:user_id]), class:"feed-btn"
  div.upload-form
    = form_with model: @post_info, local: true do |f|
      p 
        = f.label :Image, class: "image-label"
      = f.file_field :post_image, class: "image-post"
      p
        = f.label :Content
      = f.text_field :content_text
      p
        = f.submit "Post", class: "upload-submit-btn"